### ISSUE TITLE
Ridesharing Screen: Offer Ride Doubles

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#102]
On the Ridesharing home screen, the list populates double after going through the steps to offer a ride if you offer a second ride. The issue resolves if you exit the app and restart it. 

iOS Version: 10.3.3
App Version: 1.4 (4)
Phone: iPhone 6s

**Comment by tydahlwave** [comment]
Irrelevant as of version 2.0
