### ISSUE TITLE
Community Groups Screen: None Available

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#103]
On the Community Groups Screen, no Community Groups are available for me to join, even though I am subscribed to ministries. The screen saying "No community groups available! Try changing your subscribed ministries or campuses in Settings" shows up. I am subscribed to Cru Cal Poly so there should be a lot of them. This is new in 1.4 (5)

iOS Version: 10.3.3
App Version: 1.4 (5)
Phone: iPhone 6

**Comment by tydahlwave** [comment]
This is fixed as of 09/18/17. Not sure how. I assume Kyle Reis.
