### ISSUE TITLE
App Crash: Ridesharing Extreme Cases

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#104]
On the Ridesharing screen, the app crashes when trying to offer a ride for 45 people within a 3 mile radius of an address. Not sure why the app lets you go as high as 45. Maybe limit to 15? This came in from a beta tester.

iOS Version: 10.3.3
App Version: 1.4 (4)
Phone: iPhone 7

**Comment by esolum** [comment]
@kyle-fletcher The limit is currently 50, which I think is from the initial requirements discussions we had back in capstone. Maybe we were thinking about buses or something, but I'll definitely lower that to 15.
