### ISSUE TITLE
App Crash: RideSharing find ride

### ISSUE THREAD

**Issue by fedorareis** [CruCentralCoast/CruiOS#107]
Steps to Recreate:
1. Go to RideSharing
2. Click Find Ride
3. Select Fall Retreat as the Event
4. Select the only ride available (Oct. 20, 7PM)
5. Fill in name and phone number properly
6. Click Submit
7. App Crashes

Device Info:
Device Type: iPhone SE
OS: 11.0

**Comment by esolum** [comment]
Pretty sure this won't happen when the new version of the app is pushed to Testflight. I tested it with the develop branch and can't reproduce the crash.

**Comment by fedorareis** [comment]
Confirmed, fixed in new version.
