### ISSUE TITLE
Resources: Article Loads

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#115]
On the Resources section, the articles don't load to the bottom of the screen, so it doesn't look like there are additional resources if you scroll down. It should fill to the bottom of the screen or to below the bottom of the screen, so that it is obvious that you can scroll.

iOS Version: 10.3.3
App Version: 1.4 (6)
Phone: iPhone 6

![img_1150](https://user-images.githubusercontent.com/5009162/30573667-022cdef4-9caa-11e7-9d52-2d81a2b8bcae.PNG)

**Comment by kyle-fletcher** [comment]
There are currently over a dozen articles in the database, but only two are showing until you scroll. So the blank bottom of the screen makes it confusing.

**Comment by tydahlwave** [comment]
I'm not seeing this...
![img_3783](https://user-images.githubusercontent.com/4985998/30573791-a0438b06-9caa-11e7-8e28-9525db1b9fb8.PNG)

**Comment by kyle-fletcher** [comment]
It's definitely still doing it. It looks like it's picking a random number of them. Here's the one I did just now. It has 3 instead of 2, but still is not filling them out to the bottom. 

![img_1151](https://user-images.githubusercontent.com/5009162/30576227-64c684e6-9cbb-11e7-9583-d61b7910fc9a.PNG)
