### ISSUE TITLE
Event Details Screen: All Events are Location TBD

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#116]
On the Event Details screen, all events are showing TBD for location, even if there is location data in the database that shows on the main Events screen. Only events that don't have a location should show the TBD value on the Events Detail screen. 

iOS Version: 10.3.3
App Version: 1.4 (6)
Phone: iPhone 6

**Comment by esolum** [comment]
@fedorareis  this is because the locationTBD variable is set to true automatically for all events, even existing events with locations. Would recommend setting it to false.

**Comment by fedorareis** [comment]
@esolum This should be fixed now. I just switched the default on the server and it appears based on a quick spot check that the events that have locations don't have the TBD field checked.
