### ISSUE TITLE
App Crash: Editing Community Group

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#119]
As a user that leads a Community Group, the user should be able to edit their group with information about time and day of the week. Currently, the app crashes on tapping "Edit Group" from within the Community Group page after the user taps their group. This doesn't allow for editing to occur. 

App Version: 1.4 (7)
iOS Version: 11.0
Phone: iPhone 6

**Comment by fedorareis** [comment]
@kyle-fletcher I can’t reproduce this behavior on my phone. What Group is the leader the leader of?

**Comment by kyle-fletcher** [comment]
It's my group. The one that appears for Kyle Fletcher. Which is a little strange, because it doesn't show me as the leader, yet still pops up for me once I sign in. The Leader field is blank on the Community Group screen.
