### ISSUE TITLE
Ministry Team Screen: Wrong Pictures

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#120]
On the Ministry Team screen, the app is not displaying the correct pictures from the database. To see this error, compare the Team Image for Graphic Design to the image on the app. They are different which means the app is not pulling the images correctly. 

App Version: 1.4 (7)
iOS Version: 11.0
Phone: iPhone 6

**Comment by fedorareis** [comment]
The pictures are from 2 years ago when Capstone was still working on the app. Which means it is either still using cached versions of the pictures or it is looking in the wrong place.

**Comment by landongerrits** [comment]
fixed ministry team photos should now load properly. Photos uploaded to server still need to be cropped to fit in the view without cutting off faces
