### ISSUE TITLE
Event Search: Results Covered by Search Bar

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#122]
Two Issues: 
1. When searching for an Event on the Event Screen, the search bar covers the results of your search after typing something in. 
2. All events are shown with a white square around them on the main event screen, so the results displayed after the search should also include that white square

iOS Version: 11.0
App Version: 1.7 (4)
Phone: iPhone 6

![img_1158](https://user-images.githubusercontent.com/5009162/30775836-9be21b50-a050-11e7-9cfb-2bc8c632fa28.PNG)

**Comment by kyle-fletcher** [comment]
In order to reproduce, you need to search for something, then tap to open the event that is displayed as a result, and then back out.

**Comment by kyle-fletcher** [comment]
Additional Issue: When searching for something that has multiple results, the results are overlaid on top of each other. 

![img_1164](https://user-images.githubusercontent.com/5009162/30776379-17dd171a-a05a-11e7-873c-633e1e96ef93.PNG)

**Comment by tydahlwave** [comment]
@micantre What's the progress on this?

**Comment by macdude95** [comment]
I fixed issue 2 and the "additional issue", but i havent been able to figure out issue 1 yet
I BELEIVE i pushed my changes for the fixes i did finish

**Comment by tydahlwave** [comment]
Ok cool

**Comment by tydahlwave** [comment]
Irrelevant as of version 2.0
