### ISSUE TITLE
Resources Screen: Search Window

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#124]
When searching for a Resource, two issues come up. 

1. On the search pop-up screen, there is nothing to indicate that more tags are available by scrolling down. I only realized they were there because I put additional ones into the database. 

2. On the search pop-up screen, it would be great if the screen wasn't black behind the search window. Either the background should be a blurred version of what was previously seen or we should use the grey being used everywhere else in the app. 

iOS Version: 11.0
App Version: 1.4 (7)
Phone: iPhone 6

![img_1162](https://user-images.githubusercontent.com/5009162/30775907-b6f7ea2c-a051-11e7-8627-ea1c2634a069.PNG)

**Comment by tydahlwave** [comment]
1. Fixed by Tyler
2. Fixed by Erica
