### ISSUE TITLE
Join Ride Screen: Times are Confusing

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#125]
On the Join Ride Screen, when attempting to join a ride from a posted driver, the times are very confusing. The app is currently using the leave time for the driver (which is correct) so that the user knows what time they will be picked up. But it shows another time to the right (which is confusing). That time is currently the event start time, so it definitely needs to be labeled or changed. Ideas could be to label the Driver time as "Leave Time" and the time to the right as "Event Start" or "Event End". Other solutions are possible too. 

For Drivers leaving arriving late to the event, preference would be for the app to put something in Red in that section saying "This Driver is leaving after the start time of the event. You will arrive late." And if the Driver is leaving early from the Event, preference would be for the app to put something in Red in that section saying "This Driver is leaving before the end time of the event. You will miss part of the event."

iOS Version: 11.0 
App Version: 1.4 (7)
Phone: iPhone 6

![img_1163](https://user-images.githubusercontent.com/5009162/30776039-ea16a18a-a053-11e7-9626-91284dcc9f28.PNG)

**Comment by tydahlwave** [comment]
Irrelevant as of version 2.0
