### ISSUE TITLE
Offer Ride Screen: Keyboard

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#126]
On the Offer Ride screen, when typing in your phone number, choosing an event, a date, etc, the keyboard pops up and doesn't change when moving between options. So if you put your phone number in and move to the date box, then it leaves the number keypad up. Or if you do the event picker and then move on to date, it leaves the event picker up. See pictures below.

Additional Issue: On the event picker, it always says Fall Retreat right above the event picker, even if you select a different event. 

Additional Issue: There is no "done" button on the event picker, so you can't get it to go away to move on to another section. 

iOS Version: 11.0
App Version: 1.4 (11)
Phone: iPhone 6

Date appears, but event picker stays up:
![img_1165](https://user-images.githubusercontent.com/5009162/30776650-1879edec-a05f-11e7-9c84-3598f21d0800.PNG)

Fall Retreat is always showing:
![img_1166](https://user-images.githubusercontent.com/5009162/30776655-2a068368-a05f-11e7-86dd-2fed0cf9e82b.PNG)

**Comment by kyle-fletcher** [comment]
No keyboard "done" on Available Seats either.

**Comment by tydahlwave** [comment]
Irrelevant as of version 2.0
