### ISSUE TITLE
App Crash: Edit Driver

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#127]
After signing up to drive to an event, going back to edit that driving causes an app crash on "save". 

Causes two other issues:
1) After relaunching the app, the app automatically crashes (it needs Ridesharing info on the Home Screen).

2) If you download the app again to eliminate the ride from your version of the app, the app crashes for everyone on "Find Ride" section. 

iOS Version: 11.0
App Version: 1.4 (11)
Phone: iPhone 6

**Comment by tydahlwave** [comment]
Irrelevant as of version 2.0
