### ISSUE TITLE
Offer Ride: Pick Radius

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#128]
On the Pick Radius section of the Offer Ride screen, there is no one to select a new number. Pressing anything on the keyboard changes nothing and then there is no done button to finish it out. 

iOS Version: 11.0
App Version: 1.4 (11)
Phone: iPhone 6

**Comment by kyle-fletcher** [comment]
Reproduce by selecting available number of seats first. The keyboard stays up when moving to ride radius.

**Comment by cstock123** [comment]
Additional Issue: If you click on the "First Name" Text field then scroll down and click on the "Departure Date" text field, you will get trapped in a screen with no way to get out.

**Comment by tydahlwave** [comment]
Irrelevant as of version 2.0
