### ISSUE TITLE
Offer Ride: Time

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#129]
On the Offer Ride screen OR the Edit Ride screen after signing up as a driver, the app automatically puts the current time into the Time field, even if you choose something else. The selector only lets you select times of 5 minutes, but it still puts in the current time (like 1:04 instead of 1:00 or 1:05).

iOS Version: 11.0
App Version: 1.4 (11)
Phone: iPhone 6

Offer Ride Screen:
![img_1168](https://user-images.githubusercontent.com/5009162/30776867-349cdff8-a063-11e7-85bf-83a1e08735df.PNG)

Edit Ride Screen:
![img_1169](https://user-images.githubusercontent.com/5009162/30776869-3c698560-a063-11e7-9c16-5672d1e4497d.PNG)

**Comment by tydahlwave** [comment]
Irrelevant as of version 2.0
