### ISSUE TITLE
Join Ride: Map Picture

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#130]
On the Join Ride section, the Map Picture is incorrect. The picture below is going from Cal Poly to Mountainbrook, yet the map shows San Francisco to San Luis Obispo. 

iOS Version: 11.0
App Version: 1.4 (11)
Phone: iPhone 6

![img_1170](https://user-images.githubusercontent.com/5009162/30776909-0adbc296-a064-11e7-9fb7-8e490cdf6769.PNG)

**Comment by tydahlwave** [comment]
Irrelevant as of version 2.0
