### ISSUE TITLE
Join Ride: My Rides Doesn't Update

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#131]
After joining a ride, it takes you back to the My Rides screen. But the ride you just joined isn't there. If you go back out to the menu and then click Ridesharing again, then your ride will appear. It should be listed in My Rides immediately.

iOS Version: 11.0
App Version: 1.4 (11)
Phone: iPhone 6

**Comment by tydahlwave** [comment]
Irrelevant as of version 2.0
