### ISSUE TITLE
My Rides: Ride Details

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#132]
After signing up for a ride to an event, tapping the ride in My Rides takes you to a ride detail screen. This screen should look identical to the sign-up screen for the ride (with the map and times listed). The sign-up screen was recently redone, so it would be replicating it in the Ride Details section. Make sure to leave the Cancel Ride button.

iOS Version: 11.0
App Version: 1.4 (11)
Phone: iPhone 6

**Comment by tydahlwave** [comment]
Irrelevant as of version 2.0
