### ISSUE TITLE
Community Group: Not all Leaders Seeing Their Group

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#136]
This is feedback from a beta user and I confirmed on her phone. Even though she is in Keystone as leading a Community Group, the app does not show her as leading a Community Group, therefore she can't edit it. I deleted her off of the Community Group, saved, and then put her back in again. This did not solve the issue. I'm not sure how widespread this problem is, but is affecting at least some of our leaders. The Community Group should show up for her as the Leader. 

iOS Version: 11.0
App Version: 1.4 (13)
Phone: iPhone 6

**Comment by kyle-fletcher** [comment]
Examples are Anna Thengvall and Anna McCreary. Doesn't work for either of them. I have their passwords if we want to test with them.

**Comment by tydahlwave** [comment]
This is caused by the app not updating its local cache when downloading new data from the server. The workaround for this is to delete and reinstall the app. Deferring to 1.5 Release.

**Comment by tydahlwave** [comment]
Irrelevant as of version 2.0
