### ISSUE TITLE
Filter Resources for Community Group Leaders

### ISSUE THREAD

**Issue by esolum** [CruCentralCoast/CruiOS#14]
Filtering for special Leader resources was part of the original project but was never implemented. Possible solution is to add a Leader tab in the top bar that appears when user is logged in.

**Comment by macdude95** [comment]
If this is still relevant, can you elaborate?

**Comment by fedorareis** [comment]
@micantre Each of the resources (both resources and resource pages) have a "restricted" field. If that field is true then only leaders should be able to see that resource. I'm not sure we ever discussed how we wanted them to appear, whether we wanted them to appear separately or inline with the rest of the resources. 

Hopefully, @kyle-fletcher has an idea about appearance. I'm not sure which of the leader categories he wants to have access to the additional resources. Currently, we have Ministry Team, Community Group, and Summer Mission Leader flags for users. I'm also not sure if we want staff to be able to see leader resources.

**Comment by kyle-fletcher** [comment]
@micantre @fedorareis These additional resources should appear for all leaders. This includes Ministry Team Leaders, Community Group Leaders, Summer Mission Leaders, and Staff. 

The issue I see with just slipping them into the current sections is that there is no easy way for a leader to know that they could log in for additional resources, meaning that they may never do so and those resources are useless. 

The original thought was to have an additional tab up top for Leader Resources. You would have to play around with the spacing. If you do want to do it that way, I would call it "Leaders" and you'll need to figure out an icon for it. You could make that section visible to everyone and then on that page, it could say that you have to sign in to see those resources. A fancy little graphic like we have in the rest of the app and a button to link to the sign-in page would be awesome.

**Comment by tydahlwave** [comment]
So right now, I assume all resources are being shown to all users?
If not, is there any way to punt this to a later release since it requires a decent refactor?

**Comment by kyle-fletcher** [comment]
If Issue #71 is set up for this release, then this issue will also need to be set up in order to protect some of our leader resources. The main articles that need to be restricted to leaders are in the Resource Pages section, which issue #71 is looking to resolve. I would say that these are relatively low priority for 1.2 release, but if we can get to them, it would be very helpful for our leaders.

**Comment by esolum** [comment]
@kyle-fletcher I'm working on a few Resources bugs now and I'm also adding the separate section for leaders that I've been meaning to put in for a while. There are fields for Users that say if they're a CG leader, ministry team leader, summer mission leader, and/or staff, so all that needs to happen is just check if any of those fields are true and then add the tab programmatically. I wouldn't suggest having the Leaders tab showing for every user, since it would basically be a useless section for the majority of the user base. For those users, I think it would be best to give them the illusion that they have access to the every feature on the app (even if they actually don't). We can have an alert pop up or something similar that notifies leaders to log in the first time they launch the app. Perhaps it could even be in the Resources section.
