### ISSUE TITLE
Home Page: Events don't appear to be sorted correctly.

### ISSUE THREAD

**Issue by fedorareis** [CruCentralCoast/CruiOS#140]
The other day when on the app the events on the homepage were out of order. See below picture for details.

![photo sep 26 2 51 15 pm](https://user-images.githubusercontent.com/6193007/31207837-7f0ff59a-a935-11e7-8e7c-d2bcf8a31644.png)

**Comment by fedorareis** [comment]
A related issue is that the Home page currently only shows 1 event, however, the events section of the app shows 4. I'm not sure if it is set up so only events within a certain timeframe (e.g. within the next week) show up or if it is a bug. If it is based on a timeframe then that needs to be made more explicit in the UI, probably with a button at the bottom that says see more events.

**Comment by kyle-fletcher** [comment]
Yeah I think the homepage does have a timeframe applied to it. 2 weeks I believe. And yeah, I agree that could be more explicit in the UI. I'm also seeing that events are out of order on the Home screen.
