### ISSUE TITLE
Resources: Video Screen

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#144]
After playing a video on the Resources section, it seems like the video stays in full screen even after you close it. The time, cell network, and battery don't return to the top, with the app instead displaying a black bar (which makes me think the full screen didn't close properly). It's fixed by closing the app and restarting it, but should be solved at some point. 

iOS 11.0.2
Version 1.4 (20)
iPhone 6

![img_1191](https://user-images.githubusercontent.com/5009162/31255798-9bda9c4e-a9e3-11e7-8854-8e2592aa6e27.png)

**Comment by tydahlwave** [comment]
Irrelevant as of version 2.0
