### ISSUE TITLE
Resources: Leaders Tab not Appearing

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#146]
After deleting the app, reinstalling and logging back in, the Leaders tab no longer appears on the Resources section of the app. This appeared before and had content in it, but may have been removed for this app release. If not intentionally removed, then it should be showing. 

iOS 11.0.2
Version 1.4 (20)
iPhone 6

**Comment by fedorareis** [comment]
The Leaders tab only appears when the user is logged in as a leader.

**Comment by kyle-fletcher** [comment]
Yes it should appear. The issue is that I am logged in and I still can't see it. Here's what I see on the login screen and on the resources screen.

![img_1193](https://user-images.githubusercontent.com/5009162/31261354-8f2b00f4-aa08-11e7-86dd-98c0e20ad435.png)
![img_1194](https://user-images.githubusercontent.com/5009162/31261355-8f2c0a76-aa08-11e7-9312-f40df751bf33.png)

**Comment by tydahlwave** [comment]
Irrelevant as of version 2.0
