### ISSUE TITLE
Persistence Issues

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#148]
The app should make sure that all data is saved when the user updates the app. This includes Community Groups, Ministry Teams, Notifications, Subscribed Ministries / Campuses, and Ridesharing info. Here is what is completed for each one.

Works Correctly: Community Groups, Subscribed Ministries / Campuses
Doesn't Work: Notifications
Unknown: Ministry Teams (app crashed upon signup on previous version) & Ridesharing (disabled)

The notifications persistence issue should probably be fixed before initial release, otherwise users will lose access to that info (including if people signed up in their Community Group) upon updating the app. 

Further testing with a working version of Ministry Teams needs to be done for persistence.

iOS 11.0.2
Version 1.4 (20)
iPhone 6

**Comment by fedorareis** [comment]
To my understanding, everything should be persistent across updates. The only time things aren't persistent is when the app is deleted and redownloaded. In that case, the only things that are persistent are things that are stored on the server and linked to a user account. @tydahlwave can you confirm that my understanding is correct?

**Comment by tydahlwave** [comment]
Everything should persist between updates of the app. New TestFlight builds do not necessarily act as updates to an app and thus data may not be persisted between TestFlight builds.

**Comment by fedorareis** [comment]
The User Notifications model and API endpoint are finished so the related notifications can now be added to the Notification Panel and will be persistent.
