### ISSUE TITLE
Login Screen: Quick UI Fix

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#149]
On the Login screen, the Settings back button on the top left scrolls into the bar at the top and shouldn't do so. 

iOS 11.0.2
Version 1.4 (20)
iPhone 6

![img_1192](https://user-images.githubusercontent.com/5009162/31261409-e18f9ae4-aa08-11e7-8ad4-6f97a5fb6351.png)

**Comment by tydahlwave** [comment]
Cannot reproduce. However, if the keyboard were going to overlap the text field, the entire view is shifted up by default. No part of our code causes that. Not sure how you got this to happen, because I can't seem to reproduce it on the simulator.

**Comment by tydahlwave** [comment]
@kyle-fletcher

**Comment by fedorareis** [comment]
@tydahlwave I can confirm the issue @kyle-fletcher reported. ![photo oct 08 3 50 43 pm](https://user-images.githubusercontent.com/6193007/31321843-0d35c0bc-ac41-11e7-9f3e-fa0d9216fd3f.png)

**Comment by tydahlwave** [comment]
Irrelevant as of version 2.0
