### ISSUE TITLE
Get Involved: Autofill Information

### ISSUE THREAD

**Issue by fedorareis** [CruCentralCoast/CruiOS#151]
For Community Groups, once you have signed up for one the user information auto-populates when signing up for future groups. However, even for logged in users they have to enter at least part of their information the first time they sign up for a group. Similarly, in the Ministry Teams section, the Name is auto-populated for logged in users but not the Phone Number.

Ideally for both sections, if the user is logged in both the Name and Phone Number should be auto-populated. If the user is not logged in then it should auto-populate across both Community Groups and Ministry Teams if the user has entered their information to sign up for one of them already.

**Comment by tydahlwave** [comment]
Irrelevant as of version 2.0
