### ISSUE TITLE
Community Group Detail Screen: Button

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#203]
On the Community Group Detail screen, the button is too low to be clickable and it won't let me scroll. Not sure if this is already fixed in the changes that are being made, but figured I would list it. 

iPhone 6 running iOS 12

![image](https://user-images.githubusercontent.com/5009162/46188754-f02efd00-c29f-11e8-9d40-3afdd3c4f7f3.png)

**Comment by landongerrits** [comment]
nice.

ya I'll work on this

**Comment by landongerrits** [comment]
fixed this on my branch. Closing issue

**Comment by tydahlwave** [comment]
Fixed on Pull Request #189
