### ISSUE TITLE
Ministry Team Details: Leader string is sometimes off screen

### ISSUE THREAD

**Issue by tydahlwave** [CruCentralCoast/CruiOS#220]
If the leader names are long enough or if there are more than two leaders, the leader string goes off screen.

![img_4434](https://user-images.githubusercontent.com/4985998/46713387-29099300-cc0b-11e8-9df7-51f84d3b1099.PNG)

**Comment by landongerrits** [comment]
not sure who fixed this/when but the string wraps to the next line on the current version on the app store
