### ISSUE TITLE
Text Cutoff on Video Section of Resources

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#51]
Each cell on the videos tab in the Resources screen displays a video and some text. Sometimes the text is partially covered and unreadable. This is fixed when choosing another tab and going back to the videos tab. - Originally submitted by Tydalwave

[https://user-images.githubusercontent.com/4985998/27465368-fb09d47c-5787-11e7-807a-14645c2870df.png](url)

**Comment by kyle-fletcher** [comment]
Confirmed as an ongoing issue by beta testers today.

**Comment by tydahlwave** [comment]
Fixed by Erica's Resources refactor
