### ISSUE TITLE
Set up Analytics through Firebase

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#56]
Should be setup to provide analytics for the following: 

Users (location, behavior), length of session, frequency of use, flow between screens, most used features, retention of users, unregistered versus registered users and what gets them there, iOS version, iPhone model, responsiveness of app, slow downs and fails (by device type and version), repetition (shows that there must have been an error)

**Comment by landongerrits** [comment]
Currently logging the following "events" with Firebase Analytics:

- Resource view loaded
- Event View loaded
     - specific event selected

- get involved section:
     - user tapped join community group
     - user tapped join ministry team
- Summer Missions view loaded

**Comment by kyle-fletcher** [comment]
That's great! Good starting place for 1.4 Release. Can you stick a view load on Settings and on Home too? With all those, it would give us great info for future updates. After that, go ahead and close this issue.

**Comment by landongerrits** [comment]
All views are now being logged : )
