### ISSUE TITLE
Push Notifications through Firebase

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#57]
Notifications should be switched from GCM to Firebase. These notifications will be needed for ridesharing (driver and rider), Community Groups (when a user signs up), and Ministry Teams (when a user signs up). They should appear in the notifications section of the home screen.

**Comment by tydahlwave** [comment]
The firebase portion is working. Just have to make sure the notifications sent via server reach the phone now.

**Comment by tydahlwave** [comment]
As of commit dff64b730e9d006503ed03e02143c51c6a2ecb66

**Comment by tydahlwave** [comment]
Firebase push notifications work on develop. Untested on prod.

**Comment by tydahlwave** [comment]
Fixed as of commit eae6be678431157004ad0bbe5da4ee3fa38e6f15
