### ISSUE TITLE
New Community Group User Interface

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#59]
This includes the main Get Involved screen and the Community Group signup screen.

**Comment by kyle-fletcher** [comment]
On the Community Group signup page, when clicking "Join Group", the input for phone number is covered by the keyboard. You must hit "done" to close the keyboard before being able to move down into the phone number input box. It would be nice to be able to scroll even while the keyboard is up.

Version: iOS 10 running Beta 1.4
Phone: iPhone 6

![img_1135](https://user-images.githubusercontent.com/5009162/29900171-d43d5a46-8da4-11e7-9747-0e28fe9bba29.PNG)

**Comment by esolum** [comment]
@kyle-fletcher  I did some coding magic so now the dialog view should scroll to the text field whenever the keyboard is shown
