### ISSUE TITLE
Crashlytics Update

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#61]
The app is already set up with Crashlytics so that we can track crashes and errors, but it needs to be updated. There are instructions right on the Crashlytics page for how to do this. It looks like it is just updating the version number in the app and installing a new pod.

**Comment by tydahlwave** [comment]
We have Crashlytics via Fabric. It's working, but possibly could be updated. Deferring to 1.5 Release.

**Comment by tydahlwave** [comment]
Resolved in PR #213
