### ISSUE TITLE
Event Screen: Load Images

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#64]
When switching to the event screen, the images originally load with a placeholder image from a different event. All the events do this and it seems to randomly choose an event image to do this with. After a few seconds, it switches to the proper image for the event. It just feels a little clunky...maybe we should have a better placeholder image while the images load or figure out a different way to handle this.

Version: iOS 10 running Beta 1.4
Phone: iPhone 6

![img_1124](https://user-images.githubusercontent.com/5009162/29888774-dde4538e-8d76-11e7-8048-f9ed7ad8492c.PNG)

![img_1125](https://user-images.githubusercontent.com/5009162/29888786-e326e1d6-8d76-11e7-8cd9-5c747fd75eab.PNG)

**Comment by cbatch** [comment]
doneeee
