### ISSUE TITLE
Event Screen: Same Event Loads Multiple Times

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#65]
On the Event Screen, the same event shows up multiple times in the list after scrolling. This event is not listed twice in the database so it should only be displayed once. I only see this error after scrolling.

Version: iOS 10 running Beta 1.4
Phone: iPhone 6

![img_1126](https://user-images.githubusercontent.com/5009162/29888994-88a40c06-8d77-11e7-8fc1-415a8affb315.PNG)

**Comment by tydahlwave** [comment]
@kyle-fletcher Can you confirm this is still an issue?

**Comment by kyle-fletcher** [comment]
As far as I can tell, this issue is no longer a problem. It must have been solved with one of the updates we did.
