### ISSUE TITLE
Event Details Screen: UI Changes

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#66]
On the Event Details Screen, the text for the address is not located in line with the icon next to it and looks visually off from the other details (date, time). See Picture 1 below.

On the Event Details Screen, a long event title gets cut off even though it displays properly on the Event Screen. It should either be wrapped to the next line or the size should change. See Picture 2 below.

Version: iOS 10 running Beta 1.4
Phone: iPhone 6

![img_1128](https://user-images.githubusercontent.com/5009162/29889286-7c2b9826-8d78-11e7-8b40-936fc4c707f6.PNG)

![img_1127](https://user-images.githubusercontent.com/5009162/29889273-73bd0ba2-8d78-11e7-8f9e-eff9aca96278.PNG)

**Comment by kyle-fletcher** [comment]
Confirmed as an ongoing issue by beta testers today.

**Comment by landongerrits** [comment]
issue fixed.

Text shrinks to fit when event name is long. NOTE: Very long event names may still get cutoff

Constraint added to right side so text does not run off right side
