### ISSUE TITLE
Event Details Screen: Facebook Link

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#67]
On the Event Details Screen, tapping the Facebook icon does not take you to the Facebook event in a web browser. This happens even when the icon is not greyed out. These links do exist in the database, but the app doesn't do anything with it. The App correctly greyed out the Facebook icon if a link does not exist in the database, so this is just for the ones that do have the link. When tapping the Facebook icon, it should take you to the Facebook event page as listed in the database.

Version: iOS 10 running Beta 1.4
Phone: iPhone 6

**Comment by landongerrits** [comment]
fixed.

App checks that keystone has "https://" or "http://" in Facebook URL field and if the keystone user did not add this field, the app adds "http://" prefix and then opens URL
