### ISSUE TITLE
Resources Screen: Articles from Database

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#71]
On the Resources Screen, the articles section is only grabbing articles from the Resources section of the database. It should also be grabbing from the Resource Pages section of the database. The Resources section on the database is used to gather online articles that already have a web url. The Resource Page section on the database is used to put together articles that do not have a web url associated with them already (I believe it creates a web url for them to use). Both sets should be displayed as articles on the App.

**Comment by fedorareis** [comment]
For the Resource Pages the raw HTML is stored to the database so it would need to be inserted into some sort of web view. We could set up pages on the site that load the content but those pages would need to be setup to require proper authentication based off how accessible the resource is supposed to be.

**Comment by esolum** [comment]
I actually had no idea that the Resource Pages section even existed. Is there an API endpoint to get these Resource pages?

**Comment by fedorareis** [comment]
The API endpoint for this is documented [here].(https://github.com/CruCentralCoast/Keystone/wiki/API-Endpoints)
