### ISSUE TITLE
App Crash: Summer Mission Details Screen

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#72]
The App crashes on the Summer Mission Details Screen if you tap the "Learn More" button on the bottom of the screen. This only happens if there is no URL associated with the Summer Mission from the database. It should instead "grey out" the button.

Version: iOS 10 running Beta 1.4
Phone: iPhone 6

**Comment by tydahlwave** [comment]
Fixed by commit eb614c23f9fb0ee33a677e9934ad4277ee803db6
