### ISSUE TITLE
About Screen: Additional Thanks & Contact

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#74]
On the About Screen, we talked about having a few lines describing additional people to thank as a part of this project. Also, we wanted a way to have people contact us to report issues or get in contact with a developer, so I've included text for that below. It would probably be best to have the link below for questions as a button on the page. Please include the following in the About section of the app: 

Cru Central Coast would like to especially thank the following people and groups for their contribution towards this project: 
Cal Poly SLO Capstone Class & David Janzen: for their initial designs and building of the app
Andrew Kennedy: Initial Database Development
Erica Solum: UI/UX Development Lead
Tyler Dahl & Landon Gerritts: Development Team Leads
Kyle Reis: Database Development Lead
Jen Kinzie: Graphic Designer
Kyle Fletcher: Project Manager

For questions or to report issues on this app, please fill out this form: https://goo.gl/forms/HZLiX4R92V5QAB3y2

**Comment by esolum** [comment]
Darn,
