### ISSUE TITLE
App Crash: RideSharing Join Ride Screen

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#77]
When trying to join an existing ride, the app crashes on submit. To reproduce this error, navigate to Ridesharing screen, choose Join Ride, choose Fall Retreat and fill out your information. On Submit, the app will crash.

Version: iOS 10 running Beta 1.4
Phone: iPhone 6

![img_1132](https://user-images.githubusercontent.com/5009162/29898842-e5c4d0b2-8d9c-11e7-8841-95bd5bbe2325.PNG)

**Comment by tydahlwave** [comment]
Maybe fixed by commit dab96b4151b1e7c96aaf09c8dac773b37d9a250f

**Comment by tydahlwave** [comment]
Not fixed. Fails because server expects an Event in the JSON when joining a ride, but the app isn't sending an Event in the JSON.

**Comment by kyle-fletcher** [comment]
Confirmed as an ongoing issue by beta testers today.
