### ISSUE TITLE
Can't fill out login fields

### ISSUE THREAD

**Issue by fedorareis** [CruCentralCoast/CruiOS#90]
When I go to the login screen I can only fill out the username field if I click on the username first. The keyboard blocks the password field and the submit button. The keyboard needs to have a next button that pushes the user to the next form box. The "Done" button also should be a "Next" button in the username field and a "Submit" button in the password field which triggers the submission.

![img_6270](https://user-images.githubusercontent.com/6193007/30044333-5ea9f5c6-91b1-11e7-8b33-c446c06bbcb5.jpg)

**Comment by tydahlwave** [comment]
Fixed in commit 26ee1591bdc3f8161a0d520b3698f16289de7e65
