### ISSUE TITLE
Settings Screen: Create Account

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#92]
On the Login portion of the Settings Screen, the user should have the ability to create an account. It will need to populate the User section of the database with the new information. The app can then use that information from logging in to populate name / phone number fields throughout the app (Get Involved, Ridesharing). 

I believe in our conversation a few weeks ago, we decided that in order to sign up for a Community Group or Ministry Team, the user would need to sign in (create account if they don't have one). That condition will need to be put on those features. It would also need to be put onto Ridesharing for the drivers.

**Comment by kyle-fletcher** [comment]
Also, beta users are reporting that they don't know what type of account is needed on the login screen. This may be clarified automatically by putting in the Create Account portion. But we could consider some text specifying the need for a Cru Central Coast account.

**Comment by esolum** [comment]
@kyle-fletcher I remember we talked about the Creating Accounts feature awhile ago but decided to push it off to a future version. It definitely will take more than three days, but for now I can put some text on the login screen saying that currently only community group leaders can login. Do you think that's a good temporary solution?

**Comment by tydahlwave** [comment]
Irrelevant as of version 2.0
