### ISSUE TITLE
Home Screen: Tapping Upcoming Events

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#98]
On the Home screen, you should be able to tap the upcoming event and have it take you to the Event Details screen for that event. Beta users noted this as an issue within a few hours of the beta being available to them. 

Version: iOS 10.3.3
App Version: 1.4 (4)
Phone: iPhone 6 and 6s

**Comment by landongerrits** [comment]
fixed.

Tapping events should now take you to event page.
