### ISSUE TITLE
Ridesharing Screen: Offer Ride Keyboard

### ISSUE THREAD

**Issue by kyle-fletcher** [CruCentralCoast/CruiOS#99]
On the Offer Ride screen of the Ridesharing section, after typing in the phone number, the keyboard does not go away when you tap to select an event. The only way around this is to click done on the keyboard while you are still in the phone number box. The keyboard should automatically go away when you move to a new section on the screen. 

Version: iOS 10.3.3
App Version: 1.4 (4)
Phone: iPhone 6 and 6s

![img_1140](https://user-images.githubusercontent.com/5009162/30229422-b9e6cee0-9496-11e7-9279-6603ac090a7f.PNG)

**Comment by landongerrits** [comment]
Fixed. Both keyboard and number pad should be dismissed by tapping away.

The dialer/keyboard STILL stays up when transitioning to the map view. The goal is to change this map selector entirely, but it remains an issues.
